### ISSUE TITLE
some bugs i meet

### ISSUE THREAD

**Issue by maxthwell** [Vonng/hbase_fdw#1]
error message like below：
ERROR:  Error in python: TTransportException
DETAIL:  TTransportException(message='TSocket read 0 bytes', type=4)

que:
why there has no error when i use happybase only by phton script but show error like top by hbase_fdw?
other error eg:
insert 1000 rows,but can find only 900 rows in hbase,but have no tip in postgresql.

**Comment by Vonng** [comment]
for the first problem, Maybe there's something different in [happybase.Connection](https://happybase.readthedocs.io/en/stable/api.html#happybase.Connection) protocal settings? 

As for the insert problem, could you give more context info. like enabling debug options and paste some logs.

actually I only use it for querying. so update,insert,delete is roughly implemented without fully test..

**Comment by maxthwell** [comment]
try try again.
